### ISSUE TITLE
convert pytorch model into a bonsai model cfg file using torch.jit.trace

### ISSUE THREAD

**Issue by ItamarWilf** [ItamarWilf/pytorch-bonsai#1]
- [x] Use torch.jit.trace to create graph
- [x] Parse graph into bonsai modules
- [x] Create bonsai model cfg file from parsed model

**Comment by NitzanHod** [comment]
Bonsai Parser module solves this issue, supporting ResNet, VGG and U-Net.
In order to generalize to more models this module may be edited.
